# Generated by Django 4.2 on 2024-05-03 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Article.comment'),
        ),
        migrations.DeleteModel(
            name='Comment_Rel',
        ),
    ]
